# Generated by Django 2.2.17 on 2021-03-24 08:39

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0007_auto_20210321_1031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 3, 26, 8, 39, 26, 404317, tzinfo=utc), verbose_name="актуальность ключа"
            ),
        ),
    ]
